export const REQUESTED_STORES = new Map([
  ["1", "Steam"],
  ["11", "Humble Bundle"],
  ["13", "Uplay"],
  ["23", "GameBillet"],
  ["25", "Epic Games"],
]);

export const AAA_COMPANIES = [
  "2K",
  "Activision",
  "Aspyr",
  "Bandai Namco",
  "Bethesda",
  "Blizzard",
  "Bungie",
  "CAPCOM",
  "CD PROJEKT",
  "Deep Silver",
  "Devolver Digital",
  "Electronic Arts",
  "Focus Entertainment",
  "FromSoftware",
  "IO Interactive",
  "Koei Tecmo",
  "Konami",
  "Larian Studios",
  "Microsoft",
  "Nacon",
  "Paradox Interactive",
  "PlayStation",
  "Private Division",
  "Rockstar",
  "Saber Interactive",
  "SEGA",
  "Sony",
  "Square Enix",
  "Take-Two",
  "THQ Nordic",
  "Ubisoft",
  "Valve",
  "Warner Bros",
  "Xbox Game Studios",
  "Xbox Game Studios Publishing",
];

export const AAA_TITLE_KEYWORDS = [
  "assassin's creed",
  "battlefield",
  "call of duty",
  "civilization",
  "cyberpunk",
  "dark souls",
  "diablo",
  "dragon age",
  "elden ring",
  "fallout",
  "far cry",
  "final fantasy",
  "forza",
  "grand theft auto",
  "halo",
  "hogwarts legacy",
  "monster hunter",
  "nba 2k",
  "red dead redemption",
  "resident evil",
  "star wars",
  "tekken",
  "the witcher",
  "total war",
  "yakuza",
];

export const EXCLUDED_TITLE_KEYWORDS = [
  "battle pass",
  "character pass",
  "character and stage pass",
  "costume",
  "currency",
  "deluxe pack",
  "dlc",
  "expansion pass",
  "season pass",
  "skin pack",
  "stage pass",
  "soundtrack",
  "starter pack",
  "upgrade pack",
  "year pass",
];
