export const REQUESTED_STORES = new Map([
  ["1", "Steam"],
  ["11", "Humble Bundle"],
  ["13", "Uplay"],
  ["23", "GameBillet"],
  ["25", "Epic Games"],
]);

export const AAA_COMPANIES = [
  "2K",
  "Activision",
  "Aspyr",
  "Bandai Namco",
  "Bethesda",
  "Blizzard",
  "Bungie",
  "CAPCOM",
  "CD PROJEKT",
  "Deep Silver",
  "Devolver Digital",
  "Electronic Arts",
  "FromSoftware",
  "IO Interactive",
  "Koei Tecmo",
  "Konami",
  "Larian Studios",
  "Microsoft",
  "Nacon",
  "Naughty Dog",
  "Paradox Interactive",
  "PlayStation",
  "Private Division",
  "Rockstar",
  "Saber Interactive",
  "SEGA",
  "Sony",
  "Square Enix",
  "Take-Two",
  "THQ Nordic",
  "Ubisoft",
  "Valve",
  "Warner Bros",
  "Xbox Game Studios",
  "Xbox Game Studios Publishing",
];

export const AAA_TITLE_KEYWORDS = [
  "age of empires",
  "alan wake",
  "armored core",
  "assassin's creed",
  "batman arkham",
  "battlefield",
  "bioshock",
  "borderlands",
  "call of duty",
  "civilization",
  "crash bandicoot",
  "cyberpunk",
  "dark souls",
  "dead island",
  "death stranding",
  "destiny",
  "devil may cry",
  "diablo",
  "dishonored",
  "doom",
  "dragon age",
  "dragon ball",
  "dragon quest",
  "dragon's dogma",
  "dynasty warriors",
  "elden ring",
  "fallout",
  "far cry",
  "final fantasy",
  "forza",
  "gears of war",
  "ghost of tsushima",
  "god of war",
  "grand theft auto",
  "halo",
  "hitman",
  "hogwarts legacy",
  "judgment",
  "kingdom come",
  "kingdom hearts",
  "lego star wars",
  "mafia definitive",
  "mafia ii",
  "mafia iii",
  "mafia trilogy",
  "marvel's spider-man",
  "mass effect",
  "max payne",
  "metal gear",
  "metro",
  "monster hunter",
  "nba 2k",
  "nier",
  "nioh",
  "persona",
  "prey",
  "ratchet",
  "red dead redemption",
  "red dead redemption 1",
  "red dead redemption 2",
  "resident evil",
  "sekiro",
  "silent hill",
  "sniper elite",
  "sonic",
  "star wars",
  "tales of",
  "the elder scrolls",
  "the last of us",
  "the witcher",
  "tomb raider",
  "total war",
  "uncharted 4",
  "uncharted legacy of thieves",
  "uncharted the lost legacy",
  "watch dogs",
  "wolfenstein",
  "xcom",
  "yakuza",
];

export const AAA_STRONG_TITLE_KEYWORDS = [
  "age of empires",
  "alan wake",
  "armored core",
  "assassin's creed",
  "batman arkham",
  "bioshock",
  "borderlands",
  "call of duty",
  "civilization",
  "crash bandicoot",
  "cyberpunk 2077",
  "dark souls",
  "dead island",
  "death stranding",
  "devil may cry",
  "diablo",
  "dishonored",
  "doom",
  "dragon age",
  "dragon's dogma",
  "elden ring",
  "fallout",
  "far cry",
  "final fantasy",
  "forza",
  "gears of war",
  "ghost of tsushima",
  "god of war",
  "grand theft auto",
  "halo",
  "hitman",
  "hogwarts legacy",
  "kingdom come",
  "kingdom hearts",
  "mafia",
  "marvel's spider-man",
  "mass effect",
  "max payne",
  "metal gear",
  "metro 2033",
  "metro exodus",
  "metro last light",
  "metro redux",
  "monster hunter",
  "nier",
  "nioh",
  "persona",
  "ratchet",
  "red dead redemption",
  "resident evil",
  "sekiro",
  "silent hill",
  "sniper elite",
  "sonic",
  "star wars",
  "the elder scrolls",
  "the last of us",
  "the witcher",
  "tomb raider",
  "total war",
  "uncharted 4",
  "uncharted legacy of thieves",
  "uncharted the lost legacy",
  "watch dogs",
  "wolfenstein",
  "xcom",
  "yakuza",
];

export const AAA_COMPANY_ONLY_MIN_STEAM_REVIEWS = 50000;

export const SPECIAL_EDITION_KEYWORDS = [
  "anniversary edition",
  "collector's edition",
  "complete edition",
  "definitive collection",
  "definitive edition",
  "deluxe edition",
  "digital deluxe",
  "game of the year edition",
  "gold edition",
  "master edition",
  "premium edition",
  "survivor trilogy",
  "ultimate edition",
  "bundle",
];

export const RELATED_CONTENT_KEYWORDS = [
  ...SPECIAL_EDITION_KEYWORDS,
  "add-on",
  "aftermath",
  "character pass",
  "complete edition",
  "costume",
  "deluxe pack",
  "dlc",
  "expansion",
  "expansion pass",
  "the hidden ones",
  "season pass",
  "skin pack",
  "soundtrack",
  "starter pack",
  "upgrade pack",
  "year pass",
];

export const FRANCHISE_GROUPS = [
  { key: "alan-wake", label: "Alan Wake", keywords: ["alan wake"] },
  { key: "assassins-creed", label: "Assassin's Creed", keywords: ["assassin's creed", "assassins creed"] },
  { key: "borderlands", label: "Borderlands", keywords: ["borderlands"] },
  { key: "civilization", label: "Civilization", keywords: ["civilization", "sid meier's civilization", "sid meiers civilization"] },
  { key: "dead-island", label: "Dead Island", keywords: ["dead island"] },
  { key: "diablo", label: "Diablo", keywords: ["diablo"] },
  { key: "hogwarts-legacy", label: "Hogwarts Legacy", keywords: ["hogwarts legacy"] },
  { key: "metro", label: "Metro", keywords: ["metro 2033", "metro last light", "metro exodus", "metro redux"] },
  { key: "monster-hunter", label: "Monster Hunter", keywords: ["monster hunter"] },
  { key: "red-dead-redemption", label: "Red Dead Redemption", keywords: ["red dead redemption"] },
  { key: "starcraft", label: "StarCraft", keywords: ["starcraft", "starcraft ii"] },
  { key: "the-witcher", label: "The Witcher", keywords: ["the witcher", "witcher", "thronebreaker"] },
  { key: "tomb-raider", label: "Tomb Raider", keywords: ["tomb raider"] },
  { key: "uncharted", label: "Uncharted", keywords: ["uncharted"] },
  { key: "watch-dogs", label: "Watch Dogs", keywords: ["watch dogs"] },
  { key: "yakuza", label: "Yakuza", keywords: ["yakuza", "like a dragon"] },
];

export const EXCLUDED_TITLE_KEYWORDS = [
  "battle pass",
  "character pass",
  "character and stage pass",
  "add-on",
  "aftermath",
  "climb challenge",
  "costume",
  "currency",
  "deluxe pack",
  "dlc",
  ...SPECIAL_EDITION_KEYWORDS,
  "metropocre",
  "metro simulator",
  "mortal kombat",
  "expansion pass",
  "3 stars of destiny",
  "adventure game",
  "mafia sex noir",
  "season pass",
  "skin pack",
  "stage pass",
  "soundtrack",
  "street fighter",
  "swords fantasy",
  "tekken",
  "threads of destiny",
  "starter pack",
  "upgrade pack",
  "year pass",
];
