export const REQUESTED_STORES = new Map([
  ["1", "Steam"],
  ["11", "Humble Bundle"],
  ["13", "Uplay"],
  ["23", "GameBillet"],
  ["25", "Epic Games"],
]);

export const AAA_COMPANIES = [
  "2K",
  "Activision",
  "Aspyr",
  "Bandai Namco",
  "Bethesda",
  "Blizzard",
  "Bungie",
  "CAPCOM",
  "CD PROJEKT",
  "Deep Silver",
  "Devolver Digital",
  "Electronic Arts",
  "FromSoftware",
  "IO Interactive",
  "Koei Tecmo",
  "Konami",
  "Larian Studios",
  "Microsoft",
  "Nacon",
  "Paradox Interactive",
  "PlayStation",
  "Private Division",
  "Rockstar",
  "Saber Interactive",
  "SEGA",
  "Sony",
  "Square Enix",
  "Take-Two",
  "THQ Nordic",
  "Ubisoft",
  "Valve",
  "Warner Bros",
  "Xbox Game Studios",
  "Xbox Game Studios Publishing",
];

export const AAA_TITLE_KEYWORDS = [
  "age of empires",
  "alan wake",
  "armored core",
  "assassin's creed",
  "batman arkham",
  "battlefield",
  "bioshock",
  "borderlands",
  "call of duty",
  "civilization",
  "crash bandicoot",
  "cyberpunk",
  "dark souls",
  "dead island",
  "death stranding",
  "destiny",
  "devil may cry",
  "diablo",
  "dishonored",
  "doom",
  "dragon age",
  "dragon ball",
  "dragon quest",
  "dragon's dogma",
  "dynasty warriors",
  "elden ring",
  "fallout",
  "far cry",
  "final fantasy",
  "forza",
  "gears of war",
  "ghost of tsushima",
  "god of war",
  "grand theft auto",
  "halo",
  "hitman",
  "hogwarts legacy",
  "judgment",
  "kingdom come",
  "kingdom hearts",
  "lego star wars",
  "mafia",
  "marvel's spider-man",
  "mass effect",
  "max payne",
  "metal gear",
  "metro",
  "monster hunter",
  "mortal kombat",
  "nba 2k",
  "nier",
  "nioh",
  "persona",
  "prey",
  "ratchet",
  "red dead redemption",
  "red dead redemption 1",
  "red dead redemption 2",
  "resident evil",
  "sekiro",
  "silent hill",
  "sniper elite",
  "sonic",
  "star wars",
  "street fighter",
  "tales of",
  "tekken",
  "the elder scrolls",
  "the last of us",
  "the witcher",
  "tomb raider",
  "total war",
  "uncharted",
  "watch dogs",
  "wolfenstein",
  "xcom",
  "yakuza",
];

export const EXCLUDED_TITLE_KEYWORDS = [
  "battle pass",
  "character pass",
  "character and stage pass",
  "costume",
  "currency",
  "deluxe pack",
  "dlc",
  "expansion pass",
  "season pass",
  "skin pack",
  "stage pass",
  "soundtrack",
  "starter pack",
  "upgrade pack",
  "year pass",
];
